from __future__ import annotations

from qa_orchestrator.models import OrchestratorResult
from qa_orchestrator.text_sanitize import strip_markdown


def _clarity_label(confidence: float) -> str:
    if confidence >= 0.85:
        return "HIGH"
    if confidence >= 0.65:
        return "MEDIUM"
    return "LOW"


def _suite_topic(intent) -> str:
    mode = intent.execution_mode
    cap = intent.capability or "General QA"
    flows = ", ".join(intent.flow_ids[:3]) or "all READY flows"
    if mode == "morning_sanity":
        return f"Morning sanity · {flows}"
    if mode == "new_feature":
        return f"New feature discovery · {cap} · {flows}"
    if mode == "incident_multi_flow":
        return f"Incident triage · {cap} · related suites"
    if mode == "adhoc_parameterized":
        params = intent.params or {}
        param_hint = next(iter(params.values()), None)
        return f"Parameterized adhoc · {cap} · {param_hint or flows}"
    return f"Adhoc · {cap} · {flows}"


def _collect_evidence(result: OrchestratorResult) -> list[dict]:
    items: list[dict] = []
    for obs in result.execution.observations:
        for entry in obs.meta.get("evidence") or []:
            items.append(entry)
    return items[:20]


def build_markdown_report(
    *,
    result: OrchestratorResult,
    traces: list[dict[str, str]] | None = None,
) -> str:
    intent = result.intent
    suite = result.suite_plan
    execution = result.execution
    validation = result.validation
    discovery = result.discovery
    clarity = _clarity_label(intent.confidence)
    topic = _suite_topic(intent)
    evidence = _collect_evidence(result)

    lines = [
        "# ScoutAI · Enterprise QA Report",
        "",
        "> Generated by **ScoutAI** · Oracle APEX Endless Aisle · Inter typography",
        "",
        "## Executive summary",
        "",
        f"**Conclusion:** {result.conclusion} · **Phase {validation.phase}** · `{result.reason_code}`",
        "",
        strip_markdown(validation.summary),
        "",
        "## Request",
        f"- **Goal:** {result.goal}",
        f"- **Run type:** {result.run_type}",
        f"- **Suite topic:** {topic}",
        f"- **Execution mode:** `{intent.execution_mode}`",
        f"- **Capability:** {intent.capability or '—'}",
        f"- **Classifier:** {intent.classifier}",
        f"- **Intent clarity:** {clarity} ({intent.confidence:.0%})",
        "",
        "## Intent classification",
        "",
        strip_markdown(intent.reasoning),
        "",
        f"- **Primary flows:** {', '.join(intent.flow_ids) or '—'}",
        f"- **Supporting (DRAFT):** {', '.join(intent.supporting_flow_ids) or '—'}",
    ]
    if intent.params:
        lines.append(f"- **Parameters:** `{intent.params}`")

    if result.planning:
        planning = result.planning
        lines.extend(
            [
                "",
                "## QA planning",
                f"- **Strategy:** `{planning.strategy}`",
                f"- **Secondary:** {', '.join(planning.secondary_strategies) or '—'}",
                f"- **Risk:** {planning.risk_level}",
                f"- **Execution allowed:** {planning.execution_allowed}",
                f"- **Human approval required:** {planning.requires_human_approval}",
                f"- **Polarity:** {planning.polarity}",
                f"- **Candidate flows:** {', '.join(planning.candidate_flows[:8]) or '—'}",
                f"- **Selected flows:** {', '.join(planning.selected_flows) or '—'}",
                f"- **Coverage:** {planning.coverage_assessment}",
                f"- **Expected evidence:** {', '.join(planning.expected_evidence) or '—'}",
            ]
        )
        if planning.blocked_flows:
            lines.append(f"- **Blocked flows:** {', '.join(planning.blocked_flows[:8])}")
        if planning.next_actions:
            lines.append("- **Next actions:**")
            for action in planning.next_actions:
                lines.append(f"  - {action}")
        if planning.exploration:
            lines.extend(
                [
                    "",
                    "### Exploration contract",
                    f"- **Target URL:** {planning.exploration.target_url or '—'}",
                    f"- **Read only:** {planning.exploration.read_only}",
                    f"- **Max pages:** {planning.exploration.max_pages}",
                ]
            )
        if planning.generation:
            lines.extend(
                [
                    "",
                    "### Generation contract",
                    f"- **Objective:** {planning.generation.scenario_objective}",
                    f"- **Approval required:** {planning.generation.approval_required}",
                ]
            )

    if result.exploration:
        exp = result.exploration
        lines.extend(
            [
                "",
                "## Browser exploration",
                f"- **Status:** `{exp.status}`",
                f"- **Exploration ID:** `{exp.exploration_id}`",
                f"- **Target:** {exp.target_url or '—'}",
                f"- **Pages inspected:** {len(exp.pages)}",
                f"- **Elements discovered:** {len(exp.elements)}",
                f"- **Actions performed:** {len(exp.actions)}",
                f"- **Evidence captures:** {len(exp.evidence)}",
            ]
        )
        if exp.business_signals:
            lines.append("- **Business signals:**")
            for sig in exp.business_signals[:8]:
                lines.append(f"  - {sig}")
        if exp.warnings:
            lines.append("- **Warnings:**")
            for warn in exp.warnings[:6]:
                lines.append(f"  - {warn}")
        if exp.discovery_candidates:
            cand = exp.discovery_candidates[0]
            lines.append(f"- **Discovery candidate:** `{cand.candidate_id}` · status `{cand.status}`")

    if result.generation_result:
        gen = result.generation_result
        lines.extend(
            [
                "",
                "## Test generation",
                f"- **Status:** `{gen.status}`",
                f"- **Generation ID:** `{gen.generation_id}`",
                f"- **Flow:** {gen.flow_id}",
                f"- **Spec path:** `{gen.generated_spec_path or '—'}`",
                f"- **Blocked execution:** {gen.blocked_execution}",
            ]
        )
        if gen.validation:
            lines.append(f"- **Validation:** `{gen.validation.reason_code}` — {gen.validation.message}")
        if gen.scenario:
            lines.append(f"- **Scenario:** `{gen.scenario.scenario_id}` · {gen.scenario.status}")
        if gen.test_case:
            lines.append(f"- **Test case:** `{gen.test_case.test_case_id}` · {gen.test_case.status}")
        if gen.journal:
            lines.append(f"- **Journal:** `{gen.journal.generation_id}` · review `{gen.journal.review_status}`")

    lines.extend(
        [
            "",
            "## Suite selection (deterministic)",
        ]
    )
    for note in suite.notes:
        lines.append(f"- {note}")
    lines.append(f"- **Suite IDs:** {', '.join(suite.suite_ids) or '—'}")
    lines.append(f"- **Flows to execute:** {', '.join(suite.flow_ids) or '—'}")
    if suite.blocked_flows:
        lines.append(f"- **Blocked by execution gate:** {', '.join(suite.blocked_flows)}")

    if suite.execution_gates:
        lines.extend(
            [
                "",
                "## Execution gating",
                "",
                "Canonical rule: **APPROVED** artifact (not stale) **+** KB `sme_ready` **+** existing KB safety checks.",
                "",
            ]
        )
        executable_gates = [g for g in suite.execution_gates if g.executable]
        blocked_gates = [g for g in suite.execution_gates if not g.executable]
        if executable_gates:
            lines.append("### Executable")
            for gate in executable_gates:
                lines.append(f"- `{gate.flow_id}` · `{gate.reason_code}` — {gate.message}")
        if blocked_gates:
            lines.append("")
            lines.append("### Blocked")
            for gate in blocked_gates:
                approval = gate.approval_status or "missing"
                lines.append(
                    f"- `{gate.flow_id}` · `{gate.reason_code}` "
                    f"(approval={approval}, sme_ready={gate.in_sme_ready}) — {gate.message}"
                )

    lines.append("")
    lines.append("### Commands")
    for cmd in suite.commands:
        lines.append(f"1. `{cmd}`")

    if discovery:
        lines.extend(
            [
                "",
                "## Discovery & automation suggestions",
                f"- **Mode:** {discovery.mode} · **Pages:** {discovery.pages_crawled}",
                f"- **Seed:** {discovery.seed_url or '—'}",
            ]
        )
        for s in discovery.suggestions:
            lines.append(f"- {s}")

    lines.extend(
        [
            "",
            "## Execution",
            f"- **Executor:** {execution.mode}",
            f"- **Elapsed:** {execution.elapsed_ms} ms",
            f"- **LLM calls:** {result.llm_calls} · **Suite runs:** {result.steps}",
            f"- **Tokens:** in {result.tokens_in} / out {result.tokens_out}",
            "",
            strip_markdown(validation.summary),
            "",
        ]
    )
    if execution.error:
        lines.append(f"- **Error:** {execution.error}")
    for obs in execution.observations:
        status = "PASS" if obs.ok else "FAIL"
        lines.append(f"- [{status}] `{obs.action}` — {obs.message}")

    if evidence:
        lines.extend(["", "## Evidence (screenshots & DOM snapshots)"])
        for i, ev in enumerate(evidence[:12], start=1):
            label = ev.get("label") or f"capture-{i}"
            path = ev.get("path") or ""
            dom = ev.get("dom_path")
            url = (ev.get("meta") or {}).get("url")
            lines.append(f"- **{label}** — `{path}`")
            if dom:
                lines.append(f"  - DOM: `{dom}`")
            if url:
                lines.append(f"  - URL: {url}")

    if validation.findings:
        lines.extend(["", "## Findings"])
        for f in validation.findings:
            lines.append(f"- **{f.severity.upper()}** `{f.code}` — {f.message}")

    if result.healing_result:
        healing = result.healing_result
        lines.extend(
            [
                "",
                "## Self-healing",
                f"- **Status:** `{healing.status}` · `{healing.healing_id}`",
                f"- **Attempts:** {healing.attempts_used}",
                f"- **Message:** {healing.message}",
            ]
        )
        if healing.failure:
            lines.append(
                f"- **Failure type:** `{healing.failure.type}` · eligible={healing.failure.healing_eligible}"
            )
        if healing.proposal:
            lines.append(
                f"- **Proposal:** `{healing.proposal.status}` · confidence={healing.proposal.confidence:.2f}"
            )
            lines.append(f"- **Locator:** `{healing.proposal.old_locator}` → `{healing.proposal.new_locator}`")

    if result.kb_refs:
        lines.extend(["", "## KB refs", ", ".join(result.kb_refs)])

    if traces:
        lines.extend(["", "## Trace"])
        for t in traces:
            lines.append(f"- `{t.get('at', '')}` **{t.get('kind', 'info')}** — {t.get('message', '')}")

    lines.extend(
        [
            "",
            "## Policy",
            "- ScoutAI classifies intent; Playwright executes approved suites deterministically",
            "- Morning sanity runs all 19 READY flows with zero LLM at execution time",
            "- Execution requires APPROVED test-cases.yaml + KB sme_ready + catalog safety checks",
            "- Evidence captured on navigation and interactions during suite runs",
            "- Phase A: honest NEEDS_REVIEW until SME approves Ground Truth",
            "- New features: crawl + propose automation drafts → SME approval before promotion",
        ]
    )
    return "\n".join(lines)
