from __future__ import annotations

from qa_orchestrator.models import OrchestratorResult
from qa_orchestrator.text_sanitize import strip_markdown


def _clarity_label(confidence: float) -> str:
    if confidence >= 0.85:
        return "HIGH"
    if confidence >= 0.65:
        return "MEDIUM"
    return "LOW"


def _suite_topic(intent) -> str:
    mode = intent.execution_mode
    cap = intent.capability or "General QA"
    flows = ", ".join(intent.flow_ids[:3]) or "all READY flows"
    if mode == "morning_sanity":
        return f"Morning sanity · {flows}"
    if mode == "new_feature":
        return f"New feature discovery · {cap} · {flows}"
    if mode == "incident_multi_flow":
        return f"Incident triage · {cap} · related suites"
    if mode == "adhoc_parameterized":
        params = intent.params or {}
        param_hint = next(iter(params.values()), None)
        return f"Parameterized adhoc · {cap} · {param_hint or flows}"
    return f"Adhoc · {cap} · {flows}"


def _collect_evidence(result: OrchestratorResult) -> list[dict]:
    items: list[dict] = []
    for obs in result.execution.observations:
        for entry in obs.meta.get("evidence") or []:
            items.append(entry)
    return items[:20]


def build_markdown_report(
    *,
    result: OrchestratorResult,
    traces: list[dict[str, str]] | None = None,
) -> str:
    intent = result.intent
    suite = result.suite_plan
    execution = result.execution
    validation = result.validation
    discovery = result.discovery
    clarity = _clarity_label(intent.confidence)
    topic = _suite_topic(intent)
    evidence = _collect_evidence(result)

    lines = [
        "# ScoutAI · Enterprise QA Report",
        "",
        "> Generated by **ScoutAI** · Oracle APEX Endless Aisle · Inter typography",
        "",
        "## Executive summary",
        "",
        f"**Conclusion:** {result.conclusion} · **Phase {validation.phase}** · `{result.reason_code}`",
        "",
        strip_markdown(validation.summary),
        "",
        "## Request",
        f"- **Goal:** {result.goal}",
        f"- **Run type:** {result.run_type}",
        f"- **Suite topic:** {topic}",
        f"- **Execution mode:** `{intent.execution_mode}`",
        f"- **Capability:** {intent.capability or '—'}",
        f"- **Classifier:** {intent.classifier}",
        f"- **Intent clarity:** {clarity} ({intent.confidence:.0%})",
        "",
        "## Intent classification",
        "",
        strip_markdown(intent.reasoning),
        "",
        f"- **Primary flows:** {', '.join(intent.flow_ids) or '—'}",
        f"- **Supporting (DRAFT):** {', '.join(intent.supporting_flow_ids) or '—'}",
    ]
    if intent.params:
        lines.append(f"- **Parameters:** `{intent.params}`")

    lines.extend(
        [
            "",
            "## Suite selection (deterministic)",
        ]
    )
    for note in suite.notes:
        lines.append(f"- {note}")
    lines.append(f"- **Suite IDs:** {', '.join(suite.suite_ids) or '—'}")
    lines.append(f"- **Flows to execute:** {', '.join(suite.flow_ids) or '—'}")
    lines.append("")
    lines.append("### Commands")
    for cmd in suite.commands:
        lines.append(f"1. `{cmd}`")

    if discovery:
        lines.extend(
            [
                "",
                "## Discovery & automation suggestions",
                f"- **Mode:** {discovery.mode} · **Pages:** {discovery.pages_crawled}",
                f"- **Seed:** {discovery.seed_url or '—'}",
            ]
        )
        for s in discovery.suggestions:
            lines.append(f"- {s}")

    lines.extend(
        [
            "",
            "## Execution",
            f"- **Executor:** {execution.mode}",
            f"- **Elapsed:** {execution.elapsed_ms} ms",
            f"- **LLM calls:** {result.llm_calls} · **Suite runs:** {result.steps}",
            f"- **Tokens:** in {result.tokens_in} / out {result.tokens_out}",
            "",
            strip_markdown(validation.summary),
            "",
        ]
    )
    if execution.error:
        lines.append(f"- **Error:** {execution.error}")
    for obs in execution.observations:
        status = "PASS" if obs.ok else "FAIL"
        lines.append(f"- [{status}] `{obs.action}` — {obs.message}")

    if evidence:
        lines.extend(["", "## Evidence (screenshots & DOM snapshots)"])
        for i, ev in enumerate(evidence[:12], start=1):
            label = ev.get("label") or f"capture-{i}"
            path = ev.get("path") or ""
            dom = ev.get("dom_path")
            url = (ev.get("meta") or {}).get("url")
            lines.append(f"- **{label}** — `{path}`")
            if dom:
                lines.append(f"  - DOM: `{dom}`")
            if url:
                lines.append(f"  - URL: {url}")

    if validation.findings:
        lines.extend(["", "## Findings"])
        for f in validation.findings:
            lines.append(f"- **{f.severity.upper()}** `{f.code}` — {f.message}")

    if result.kb_refs:
        lines.extend(["", "## KB refs", ", ".join(result.kb_refs)])

    if traces:
        lines.extend(["", "## Trace"])
        for t in traces:
            lines.append(f"- `{t.get('at', '')}` **{t.get('kind', 'info')}** — {t.get('message', '')}")

    lines.extend(
        [
            "",
            "## Policy",
            "- ScoutAI classifies intent; Playwright executes approved suites deterministically",
            "- Morning sanity runs all 19 READY flows with zero LLM at execution time",
            "- Evidence captured on navigation and interactions during suite runs",
            "- Phase A: honest NEEDS_REVIEW until SME approves Ground Truth",
            "- New features: crawl + propose automation drafts → SME approval before promotion",
        ]
    )
    return "\n".join(lines)
